#include "App/MainWindow.h"
#include "UI/MainToolBar.h"
#include "UI/TrackPanel.h"
#include "UI/ParameterPanel.h"
#include "UI/TransportBar.h"
#include "UI/PreferencesDialog.h"
#include "UI/DiagnosticsDialog.h"
#include "Utils/Logger.h"
#include <QDockWidget>
#include <QFileDialog>
#include <QMenuBar>
#include <QMessageBox>
#include <QProgressDialog>
#include <QStatusBar>
#include <QApplication>
#include <QKeyEvent>
#include <QWheelEvent>
#include <QDir>
#include <QSettings>
namespace myvocal {
MainWindow::MainWindow(QWidget*p):QMainWindow(p),m_renderer(&m_singers,this){m_project=std::make_unique<Project>();buildUi();buildMenus();connectUi();m_singers.scan(QDir::currentPath().toStdString()+std::string("/VoiceBanks"));setWindowTitle("MyVocalSynth");resize(1280,820);}
void MainWindow::buildUi(){m_toolbar=new MainToolBar(this);addToolBar(Qt::TopToolBarArea,m_toolbar);m_trackPanel=new TrackPanel(m_project.get(),this);auto*td=new QDockWidget("Tracks",this);td->setWidget(m_trackPanel);addDockWidget(Qt::LeftDockWidgetArea,td);m_editor=new PianoRollEditor(m_project.get(),this);setCentralWidget(m_editor);m_params=new ParameterPanel(m_project.get(),this);auto*pd=new QDockWidget("Parameters",this);pd->setWidget(m_params);addDockWidget(Qt::BottomDockWidgetArea,pd);m_transport=new TransportBar(&m_audio,this);statusBar()->addPermanentWidget(m_transport,1);}
void MainWindow::buildMenus(){auto*file=menuBar()->addMenu("File");file->addAction("New",this,&MainWindow::newProject,QKeySequence::New);file->addAction("Open",this,&MainWindow::openProject,QKeySequence::Open);file->addAction("Save",this,&MainWindow::saveProject,QKeySequence::Save);file->addAction("Save As",this,&MainWindow::saveProjectAs,QKeySequence::SaveAs);file->addSeparator();file->addAction("Import MIDI",this,&MainWindow::importMidi);file->addAction("Export WAV",this,&MainWindow::exportWav);file->addSeparator();file->addAction("Exit",qApp,&QApplication::quit);auto*edit=menuBar()->addMenu("Edit");edit->addAction("Undo",[this]{m_undo.undo();m_editor->update();},QKeySequence::Undo);edit->addAction("Redo",[this]{m_undo.redo();m_editor->update();},QKeySequence::Redo);edit->addAction("Select All",[this]{for(auto&n:m_project->tracks()[0].notes())n.setSelected(true);m_editor->update();},QKeySequence::SelectAll);edit->addAction("Delete",[this]{m_editor->setFocus();QKeyEvent e(QEvent::KeyPress,Qt::Key_Delete,Qt::NoModifier);QApplication::sendEvent(m_editor,&e);},QKeySequence::Delete);auto*track=menuBar()->addMenu("Track");track->addAction("Add Track",this,&MainWindow::addTrack);track->addAction("Delete Track",this,&MainWindow::removeTrack);auto*singer=menuBar()->addMenu("Singer");singer->addAction("Refresh Singer",[this]{m_singers.scan(QDir::currentPath().toStdString()+std::string("/VoiceBanks"));});singer->addAction("Singer Settings",this,&MainWindow::showDiagnostics);auto*tools=menuBar()->addMenu("Tools");tools->addAction("Rescan Voicebanks",[this]{m_singers.scan(QDir::currentPath().toStdString()+std::string("/VoiceBanks"));});tools->addAction("Rescan Resamplers",[this]{});tools->addAction("Clear Cache",[]{});tools->addAction("Preferences",this,&MainWindow::showPreferences);tools->addAction("Debug Window",this,&MainWindow::showDiagnostics);auto*view=menuBar()->addMenu("View");view->addAction("Zoom In",[this]{QWheelEvent e(QPointF(),QPointF(),QPoint(),QPoint(120,0),Qt::NoButton,Qt::NoModifier,Qt::ScrollUpdate,false);QApplication::sendEvent(m_editor,&e);});view->addAction("Show Grid",[this]{});auto*render=menuBar()->addAction("Render",this,&MainWindow::renderProject);render->setShortcut(QKeySequence("Ctrl+R"));}
void MainWindow::connectUi(){connect(m_toolbar,&MainToolBar::toolChanged,this,&MainWindow::setTool);connect(m_toolbar,&MainToolBar::snapToggled,m_editor,&PianoRollEditor::setSnapEnabled);connect(m_toolbar,&MainToolBar::gridToggled,m_editor,&PianoRollEditor::setShowGrid);connect(m_trackPanel,&TrackPanel::trackSelected,this,&MainWindow::selectTrack);connect(m_editor,&PianoRollEditor::documentChanged,this,[this]{updateTitle();});connect(m_transport,&TransportBar::playPause,this,&MainWindow::togglePlay);connect(m_transport,&TransportBar::stopPressed,this,&MainWindow::stopPlayback);}
void MainWindow::newProject(){setProject(std::make_unique<Project>());}void MainWindow::openProject(){auto p=QFileDialog::getOpenFileName(this,"Open Project",{},"MyVocalSynth Project (*.vocalproj);;All Files (*)");if(p.isEmpty())return;QString e;auto pr=Project::load(std::filesystem::path(p.toStdString()),&e);if(!pr){QMessageBox::critical(this,"Open failed",e);return;}setProject(std::move(pr));}
void MainWindow::saveProject(){if(m_project->path().empty())saveProjectAs();else{QString e;if(!m_project->save(m_project->path(),&e))QMessageBox::critical(this,"Save failed",e);}}void MainWindow::saveProjectAs(){auto p=QFileDialog::getSaveFileName(this,"Save Project",{},"MyVocalSynth Project (*.vocalproj)");if(p.isEmpty())return;QString e;if(m_project->save(std::filesystem::path(p.toStdString()),&e)){m_project->setPath(std::filesystem::path(p.toStdString()));updateTitle();}else QMessageBox::critical(this,"Save failed",e);}
void MainWindow::importMidi(){QMessageBox::information(this,"MIDI", "MIDI import is reserved for the MIDI module in the next implementation phase.");}
void MainWindow::exportWav(){auto p=QFileDialog::getSaveFileName(this,"Export WAV",{},"WAV (*.wav)");if(p.isEmpty())return;QString e;if(!m_renderer.renderProject(*m_project,p,&e))QMessageBox::warning(this,"Render",e);}
void MainWindow::addTrack(){m_project->addTrack();m_trackPanel->refresh();m_editor->setActiveTrack(m_project->tracks().size()-1);updateTitle();}void MainWindow::removeTrack(){if(m_project->tracks().size()<=1)return;m_project->removeTrack(m_project->tracks().size()-1);m_trackPanel->refresh();m_editor->setActiveTrack(0);updateTitle();}void MainWindow::selectTrack(int i){m_editor->setActiveTrack(i);}void MainWindow::setTool(EditTool t){m_editor->setTool(t);}void MainWindow::togglePlay(){if(m_audio.isPlaying())m_audio.pause();else m_audio.play();}void MainWindow::stopPlayback(){m_audio.stop();}
void MainWindow::renderProject(){renderSelected();}void MainWindow::renderSelected(){auto p=QFileDialog::getSaveFileName(this,"Render Project",{},"WAV (*.wav)");if(p.isEmpty())return;QProgressDialog dlg("Rendering...","Cancel",0,100,this);dlg.setWindowModality(Qt::WindowModal);connect(&m_renderer,&Renderer::progress,&dlg,&QProgressDialog::setValue);QString e;const bool ok=m_renderer.renderProject(*m_project,p,&e);dlg.setValue(100);if(ok){m_audio.load(p);QMessageBox::information(this,"Render","Render complete.");}else QMessageBox::warning(this,"Render",e);}
void MainWindow::showPreferences(){PreferencesDialog d(&m_resampler,this);d.exec();m_renderer.setResampler(m_resampler);}void MainWindow::showDiagnostics(){QString s="Voicebank Diagnostic\n\n";for(const auto&v:m_singers.singers())s+=QString("Singer: %1\noto.ini: %2\nAliases: %3\n\n").arg(v->info().name).arg(v->isValid()?"OK":"ERROR").arg(v->oto().getEntries().size());DiagnosticsDialog d(s,this);d.exec();}
void MainWindow::setProject(std::unique_ptr<Project>p){m_project=std::move(p);m_editor->deleteLater();m_trackPanel->deleteLater();m_params->deleteLater();m_editor=new PianoRollEditor(m_project.get(),this);setCentralWidget(m_editor);m_trackPanel=new TrackPanel(m_project.get(),this);for(auto*dock:findChildren<QDockWidget*>()){if(dock->windowTitle()=="Tracks")dock->setWidget(m_trackPanel);}m_params=new ParameterPanel(m_project.get(),this);for(auto*dock:findChildren<QDockWidget*>()){if(dock->windowTitle()=="Parameters")dock->setWidget(m_params);}m_undo.clear();updateTitle();connect(m_trackPanel,&TrackPanel::trackSelected,this,&MainWindow::selectTrack);}void MainWindow::updateTitle(){setWindowTitle(QStringLiteral("%1 — MyVocalSynth").arg(m_project->title()));}QString MainWindow::defaultProjectPath()const{return QString();}
}
