#include "Core/Project.h"
#include <QFile>
#include <QJsonDocument>
#include <QJsonArray>
#include <QJsonObject>
#include <QSaveFile>
#include <algorithm>
namespace myvocal { Project::Project(){m_tracks.push_back(Track(0));} double Project::ppq()const noexcept{return m_ppq;} TempoMap&Project::tempoMap()noexcept{return m_tempo;} const TempoMap&Project::tempoMap()const noexcept{return m_tempo;} int Project::timeSignatureNumerator()const noexcept{return m_tsN;} int Project::timeSignatureDenominator()const noexcept{return m_tsD;} void Project::setTimeSignature(int n,int d){m_tsN=std::max(1,n);m_tsD=std::max(1,d);} QVector<Track>&Project::tracks()noexcept{return m_tracks;} const QVector<Track>&Project::tracks()const noexcept{return m_tracks;} Track&Project::addTrack(){m_tracks.push_back(Track(m_tracks.size()));return m_tracks.back();} bool Project::removeTrack(int i){if(i<0||i>=m_tracks.size()||m_tracks.size()==1)return false;m_tracks.removeAt(i);return true;} std::filesystem::path Project::path()const{return m_path;}void Project::setPath(const std::filesystem::path&p){m_path=p;} QString Project::title()const{return m_title;}void Project::setTitle(const QString&s){m_title=s;}
bool Project::save(const std::filesystem::path&p,QString*error)const{QSaveFile f(QString::fromStdString(p.string()));if(!f.open(QIODevice::WriteOnly)){if(error)*error=f.errorString();return false;}QJsonObject root;root["formatVersion"]=1;root["title"]=m_title;root["ppq"]=m_ppq;root["tempo"]=m_tempo.bpm();QJsonObject ts;ts["numerator"]=m_tsN;ts["denominator"]=m_tsD;root["timeSignature"]=ts;QJsonArray tracks;for(const auto&t:m_tracks){QJsonObject to;to["id"]=t.id();to["name"]=t.name();to["mute"]=t.muted();to["solo"]=t.solo();to["volume"]=t.volume();to["pan"]=t.pan();to["singer"]=t.singerPath();to["phonemizer"]=t.phonemizer();QJsonArray notes;for(const auto&n:t.notes())notes.append(n.serialize());to["notes"]=notes;tracks.append(to);}root["tracks"]=tracks;f.write(QJsonDocument(root).toJson(QJsonDocument::Indented));if(!f.commit()){if(error)*error=f.errorString();return false;}return true;}
std::unique_ptr<Project> Project::load(const std::filesystem::path&p,QString*error){QFile f(QString::fromStdString(p.string()));if(!f.open(QIODevice::ReadOnly)){if(error)*error=f.errorString();return nullptr;}QJsonParseError pe;auto doc=QJsonDocument::fromJson(f.readAll(),&pe);if(pe.error!=QJsonParseError::NoError||!doc.isObject()){if(error)*error=pe.errorString();return nullptr;}auto pr=std::make_unique<Project>();auto r=doc.object();pr->m_path=p;pr->m_title=r["title"].toString("Untitled");pr->m_ppq=r["ppq"].toDouble(480);pr->m_tempo.setBpm(r["tempo"].toDouble(120));auto ts=r["timeSignature"].toObject();pr->setTimeSignature(ts["numerator"].toInt(4),ts["denominator"].toInt(4));pr->m_tracks.clear();for(const auto&tv:r["tracks"].toArray()){auto to=tv.toObject();Track t(to["id"].toInt(pr->m_tracks.size()));t.setName(to["name"].toString(t.name()));t.setMuted(to["mute"].toBool());t.setSolo(to["solo"].toBool());t.setVolume(to["volume"].toDouble(1));t.setPan(to["pan"].toDouble());t.setSingerPath(to["singer"].toString());t.setPhonemizer(to["phonemizer"].toString("Default CV"));for(const auto&nv:to["notes"].toArray())t.addNote(Note::deserialize(nv.toObject()));pr->m_tracks.push_back(std::move(t));}if(pr->m_tracks.isEmpty())pr->m_tracks.push_back(Track(0));return pr;}
}
